# Properties
---
acme:
  list:
    - name: my name
      description: my description
    - name: another name
      description: another description
lucky-word: Lucky
---
spring:
  profiles: dev
acme:
  list:
    - name: my another name
