# Properties
---
lucky-word: Lucky
acme:
  list:
    - name: my name
      description: my description
    - name: another name
      description: another description

---
spring:
  profiles: dev
acme:
  list:
    - name: my another name
